name: Test Push Request

on: 
  push:
    branches:
      - AidanTest

jobs:
  lint-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint

      - name: Run prettier check
        run: npm run check

      - name: Run prettier write
        run: npm run format